services:
  - type: web
    name: compass-os
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: SECRET_KEY
        value: C0mp@$$$
      - key: DATABASE_URL
        value: postgresql://postgres:pYROw_2077%21%23@db.ellltlzdvbwissqfjoje.supabase.co:5432/postgres
